[workspace]
members = [
	"client/cli",
	"client/consensus/aura",
	"client/consensus/common",
	"client/consensus/relay-chain",
	"client/network",
	"client/pov-recovery",
	"client/service",
	"client/relay-chain-interface",
	"client/relay-chain-inprocess-interface",
	"client/relay-chain-rpc-interface",
	"pallets/aura-ext",
	"pallets/collator-selection",
	"pallets/dmp-queue",
	"pallets/parachain-system",
	"pallets/parachain-system/proc-macro",
	"pallets/session-benchmarking",
	"pallets/xcm",
	"pallets/xcmp-queue",
	"parachain-template/node",
	"parachain-template/runtime",
	"primitives/core",
	"primitives/parachain-inherent",
	"primitives/timestamp",
	"primitives/utility",
	"polkadot-parachain/",
	"parachains/common",
	"parachains/pallets/parachain-info",
	"parachains/pallets/ping",
	"parachains/runtimes/testing/rococo-parachain",
	"parachains/runtimes/starters/shell",
	"parachains/runtimes/starters/seedling",
	"parachains/runtimes/assets/statemint",
	"parachains/runtimes/assets/statemine",
	"parachains/runtimes/assets/westmint",
	"parachains/runtimes/collectives/collectives-polkadot",
	"parachains/runtimes/contracts/contracts-rococo",
	"parachains/runtimes/testing/penpal",
	"test/client",
	"test/relay-sproof-builder",
	"test/relay-validation-worker-provider",
	"test/runtime",
	"test/service",
]

[profile.release]
panic = "unwind"
opt-level = 3

[profile.production]
inherits = "release"
lto = true
codegen-units = 1
[patch."https://github.com/paritytech/substrate"]
cumulus-client-cli ={git = "https://github.com/paritytech/substrate" ,branch = "polkadot-v0.9.29" }
cumulus-client-consensus-aura ={git = "https://github.com/paritytech/substrate" ,branch = "polkadot-v0.9.29" }
cumulus-client-consensus-common ={git = "https://github.com/paritytech/substrate" ,branch = "polkadot-v0.9.29" }
cumulus-relay-chain-interface ={git = "https://github.com/paritytech/substrate" ,branch = "polkadot-v0.9.29" }
cumulus-primitives-core ={git = "https://github.com/paritytech/substrate" ,branch = "polkadot-v0.9.29" }
cumulus-test-client ={git = "https://github.com/paritytech/substrate" ,branch = "polkadot-v0.9.29" }
cumulus-primitives-parachain-inherent ={git = "https://github.com/paritytech/substrate" ,branch = "polkadot-v0.9.29" }
cumulus-test-relay-sproof-builder ={git = "https://github.com/paritytech/substrate" ,branch = "polkadot-v0.9.29" }
cumulus-test-runtime ={git = "https://github.com/paritytech/substrate" ,branch = "polkadot-v0.9.29" }
cumulus-pallet-parachain-system ={git = "https://github.com/paritytech/substrate" ,branch = "polkadot-v0.9.29" }
cumulus-pallet-parachain-system-proc-macro ={git = "https://github.com/paritytech/substrate" ,branch = "polkadot-v0.9.29" }
cumulus-primitives-timestamp ={git = "https://github.com/paritytech/substrate" ,branch = "polkadot-v0.9.29" }
cumulus-test-service ={git = "https://github.com/paritytech/substrate" ,branch = "polkadot-v0.9.29" }
cumulus-client-consensus-relay-chain ={git = "https://github.com/paritytech/substrate" ,branch = "polkadot-v0.9.29" }
cumulus-client-network ={git = "https://github.com/paritytech/substrate" ,branch = "polkadot-v0.9.29" }
cumulus-relay-chain-inprocess-interface ={git = "https://github.com/paritytech/substrate" ,branch = "polkadot-v0.9.29" }
cumulus-client-service ={git = "https://github.com/paritytech/substrate" ,branch = "polkadot-v0.9.29" }
cumulus-client-collator ={git = "https://github.com/paritytech/substrate" ,branch = "polkadot-v0.9.29" }
cumulus-client-pov-recovery ={git = "https://github.com/paritytech/substrate" ,branch = "polkadot-v0.9.29" }
cumulus-relay-chain-rpc-interface ={git = "https://github.com/paritytech/substrate" ,branch = "polkadot-v0.9.29" }
cumulus-test-relay-validation-worker-provider ={git = "https://github.com/paritytech/substrate" ,branch = "polkadot-v0.9.29" }
parachains-common ={git = "https://github.com/paritytech/substrate" ,branch = "polkadot-v0.9.29" }
cumulus-primitives-utility ={git = "https://github.com/paritytech/substrate" ,branch = "polkadot-v0.9.29" }
pallet-collator-selection ={git = "https://github.com/paritytech/substrate" ,branch = "polkadot-v0.9.29" }
cumulus-pallet-aura-ext ={git = "https://github.com/paritytech/substrate" ,branch = "polkadot-v0.9.29" }
cumulus-pallet-dmp-queue ={git = "https://github.com/paritytech/substrate" ,branch = "polkadot-v0.9.29" }
cumulus-pallet-session-benchmarking ={git = "https://github.com/paritytech/substrate" ,branch = "polkadot-v0.9.29" }
cumulus-pallet-xcm ={git = "https://github.com/paritytech/substrate" ,branch = "polkadot-v0.9.29" }
cumulus-pallet-xcmp-queue ={git = "https://github.com/paritytech/substrate" ,branch = "polkadot-v0.9.29" }
parachain-template-node ={git = "https://github.com/paritytech/substrate" ,branch = "polkadot-v0.9.29" }
parachain-template-runtime ={git = "https://github.com/paritytech/substrate" ,branch = "polkadot-v0.9.29" }
pallet-template ={git = "https://github.com/paritytech/substrate" ,branch = "polkadot-v0.9.29" }
parachain-info ={git = "https://github.com/paritytech/substrate" ,branch = "polkadot-v0.9.29" }
polkadot-parachain ={git = "https://github.com/paritytech/substrate" ,branch = "polkadot-v0.9.29" }
collectives-polkadot-runtime ={git = "https://github.com/paritytech/substrate" ,branch = "polkadot-v0.9.29" }
contracts-rococo-runtime ={git = "https://github.com/paritytech/substrate" ,branch = "polkadot-v0.9.29" }
penpal-runtime ={git = "https://github.com/paritytech/substrate" ,branch = "polkadot-v0.9.29" }
rococo-parachain-runtime ={git = "https://github.com/paritytech/substrate" ,branch = "polkadot-v0.9.29" }
cumulus-ping ={git = "https://github.com/paritytech/substrate" ,branch = "polkadot-v0.9.29" }
seedling-runtime ={git = "https://github.com/paritytech/substrate" ,branch = "polkadot-v0.9.29" }
cumulus-pallet-solo-to-para ={git = "https://github.com/paritytech/substrate" ,branch = "polkadot-v0.9.29" }
shell-runtime ={git = "https://github.com/paritytech/substrate" ,branch = "polkadot-v0.9.29" }
statemine-runtime ={git = "https://github.com/paritytech/substrate" ,branch = "polkadot-v0.9.29" }
asset-test-utils ={git = "https://github.com/paritytech/substrate" ,branch = "polkadot-v0.9.29" }
statemint-runtime ={git = "https://github.com/paritytech/substrate" ,branch = "polkadot-v0.9.29" }
westmint-runtime ={git = "https://github.com/paritytech/substrate" ,branch = "polkadot-v0.9.29" }
