name: Check labels (new)

on:
  pull_request:
    types: [labeled, opened, synchronize, unlabeled]

jobs:
  check-labels:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: ${{ github.event.pull_request.head.ref }}
          repository: ${{ github.event.pull_request.head.repo.full_name }}

      - name: Pull image
        env:
          IMAGE: chevdor/ruled-labels:latest
        run: |
          docker pull $IMAGE
          docker run --rm -it $IMAGE --version

      - name: Check labels
        # continue-on-error: true
        env:
          IMAGE: chevdor/ruled-labels:latest
          MOUNT: /work
          CHECK_SPECS: specs.yaml
          GITHUB_PR: ${{ github.event.pull_request.number }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          API_BASE: https://api.github.com/repos
          REPO: ${{ github.repository }}
        run: |
          echo "REPO: $REPO"
          echo "GITHUB_PR: $GITHUB_PR"

          # Fetch the labels for the PR under test
          labels=$( curl -H "Authorization: token $GITHUB_TOKEN" -s "$API_BASE/$REPO/pulls/$GITHUB_PR" | jq '.labels | .[] | .name' | tr "\n" ",")
          labels_args=${labels: :-1}
          printf "Checking labels: %s\n" "$labels_args"

          # --dev is more useful to debug mode to debug
          docker run --rm -i -e labels_args -v $PWD/:$MOUNT $IMAGE check $MOUNT/$CHECK_SPECS --dev --labels $labels_args
