name: Check labels (new)

on:
  pull_request:
    types: [labeled, opened, synchronize, unlabeled]

jobs:
  check-labels:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: ${{ github.event.pull_request.head.ref }}
          repository: ${{ github.event.pull_request.head.repo.full_name }}

      - name: Install Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      - name: Check labels
        # continue-on-error: true
        env:
          CHECK_SPECS: specs.yaml
          GITHUB_PR: ${{ github.event.pull_request.number }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          API_BASE: https://api.github.com/repos
          REPO: ${{ github.repository }}
          RULES_PATH: scripts/ci/ruled_labels
        run: |
          cargo install ruled-labels --version 0.3.1
          echo "REPO: ${REPO}"
          echo "GITHUB_PR: ${GITHUB_PR}"

          # Fetch the labels for the PR under test
          labels=$( curl -H "Authorization: token ${GITHUB_TOKEN}" -s "$API_BASE/${REPO}/pulls/${GITHUB_PR}" | jq '.labels | .[] | .name' | tr "\n" ",")
          labels_args=${labels: :-1} || echo "Please set labels"; exit 1
          printf "Checking labels: %s\n" "${labels_args}"

          # Prevent the shell from splitting labels with spaces
          IFS=","

          # --dev is more useful to debug mode to debug
          ruled-labels check --labels ${labels_args} --dev ${RULES_PATH}/${CHECK_SPECS}
